"""Add fundraiserProduct

Revision ID: 8969a4cac986
Revises: 173af3d34637
Create Date: 2026-09-02 21:22:52.822592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8969a4cac986'
down_revision: Union[str, Sequence[str], None] = '173af3d34637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundraiser_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fundraiser_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('starting_quantity', sa.Integer(), nullable=False),
    sa.Column('ending_quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fundraiser_id'], ['fundraisers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fundraiser_id', 'product_id', name='unique_fundraiser_product')
    )
    op.create_index(op.f('ix_fundraiser_products_fundraiser_id'), 'fundraiser_products', ['fundraiser_id'], unique=False)
    op.create_index(op.f('ix_fundraiser_products_product_id'), 'fundraiser_products', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fundraiser_products_product_id'), table_name='fundraiser_products')
    op.drop_index(op.f('ix_fundraiser_products_fundraiser_id'), table_name='fundraiser_products')
    op.drop_table('fundraiser_products')
    # ### end Alembic commands ###
