"""Update constraints on Fundraisers

Revision ID: 8c2c1cb9616c
Revises: 30940e03d113
Create Date: 2026-09-05 21:09:55.744879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c2c1cb9616c'
down_revision: Union[str, Sequence[str], None] = '30940e03d113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_scheduled_fundraiser', 'fundraisers', ['organization_id', 'name', 'event_date'])
    op.create_unique_constraint(None, 'organizations', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_constraint('unique_scheduled_fundraiser', 'fundraisers', type_='unique')
    # ### end Alembic commands ###
